apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-05T05:35:36Z"
  labels:
    name: webapp-color
  name: webapp-color
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: green
    image: kodekloud/webapp-color
    name: webapp-color